server:
  port: 8082
spring:
  flyway:
    enabled: true
    url: "jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}"
    user: "${DB_USER}"
    password: "${DB_PASSWORD}"
    locations: "classpath:db/migration"
    baseline-on-migrate: true
  application:
    name: "loan-applications"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
logging:
  level:
    root: "INFO"
    co.com.bancolombia: "DEBUG"
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
springdoc:
  swagger-ui:
    path: "/swagger-ui.html"
adapters:
  r2dbc:
    host: "${DB_HOST}"
    port: "${DB_PORT}"
    database: "${DB_NAME}"
    username: "${DB_USER}"
    password: "${DB_PASSWORD}"
services:
  auth:
    url: "${AUTH_SERVICE_URL}"
jwt:
  secret: "${JWT_SECRET}"

adapter:
  sqs:
    region: "${ADAPTER_SQS_REGION}"
    queueUrl: "${ADAPTER_SQS_QUEUEURL}"      # request -> Lambda
    notificationsQueueUrl: "${ADAPTER_SQS_NOTIFICATIONSQUEUEURL}"      # request -> Lambda

entrypoint:
  sqs:
    region: "${ADAPTER_SQS_REGION}"
    queueUrl: "${ENTRYPOINT_SQS_QUEUEURL}"   # result <- Lambda
    waitTimeSeconds: 20
    maxNumberOfMessages: 10
    visibilityTimeoutSeconds: 30
    numberOfThreads: 1




