server:
  port: 8082
spring:
  application:
    name: "loan-applications"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
logging:
  level:
    root: INFO
    co.com.bancolombia: DEBUG

cors:
  allowed-origins: http://localhost:4200,http://localhost:8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html

adapters:
  r2dbc:
    host: localhost
    port: 5432
    database: prestamos
    username: postgres
    password: postgres

services:
  auth:
    url: ${AUTH.SERVICE_URL:http://localhost:8081}
